### PR TITLE
Update snapchat.php

### PR DESCRIPTION
**Pull request by md726**
Seems there went something wrong with your last update and you used an older commit for making your ')' fix.
Anyway I'm going here back to #51436f4 and keeping your ')' fix

### CODE REVIEW

**Comment by mgp25** [comment]
@mands72 this commit you are pull requesting, only changes the path of the auth, any reason for it?

**Comment by md726** [comment]
@mgp25 Ok, got you, my pull request makes in this way no sence. But there must be something more. With the current version of SnapAPI I'm always getting errors like:

PHP Notice:  unserialize(): Error at offset 0 of 32 bytes in /var/www/SnapAPI/src/snapchat.php on line 84
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/SnapAPI/src/snapchat.php on line 86
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/SnapAPI/src/snapchat.php on line 89
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/SnapAPI/src/snapchat.php on line 304
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) Client VM (build 25.0-b70, mixed mode)

It's also always logging in again instead of using the auth file (because of the errors above...). But with changing the paths it's working again. Had no time to check what's going on but anyway this fixed my issue and it's using the auth file instead of logging in again and again

**Comment by md726** [comment]
Forget about it...

**Comment by mgp25** [comment]
@mands72 remoev your previosly auth from the folder, and you are ready to go, its keeping looging in everytime the scripts run, but it will be fixed soon

Regards

**Comment by md726** [comment]
Okay, that's what I was just writing here, it's keeping logging in everytime.
Thanks so much for your quick answer! :-)

**Pull request closed without merging**
