### PR TITLE
Using getConversations() instead of conversations_response in getSnaps()

### PR DESCRIPTION
**Pull request by marank**
getSnaps() should use the return value of getConversations().

### CODE REVIEW

**Comment by marank** [comment]
I've made some more changes to Snap-API, including support for (custom) subdirectories in /snaps and /stories (since more than one auth token at once can now be stored).

Sorry for committing all my improvements at once :)

**Comment by mgp25** [comment]
https://github.com/mgp25/Snap-API/pull/91/files#diff-16d5eaf684207e73fd963264820254f2R152

Use `__DIR__` instead

**Comment by marank** [comment]
Done. Thanks for pointing out.

**Comment by mgp25** [comment]
@marank the rest of the commits are working? it seems fine to me.

**Comment by marank** [comment]
Yes they are working for me.

**Comment by mgp25** [comment]
@marank awesome, thanks :+1:

**Pull request merged**
